import { SEOWrapper } from "@/components/SEO";
import TwProduct from "@/components/tw/Product";
import FeatureSection, { TwFeatureType, TwItemPlacement } from "@/components/tw/FeatureSection";
import { IoMdAnalytics } from "react-icons/io";

const Studio = () => {
  return (
    <SEOWrapper
      title="Reticulo | Studio"
      description="A state of the art AI based Video Analytics platform which provides with valuable insights to your game. 
      Just upload your match to get results generated by Reticulo's AI. Studio provides a wide range of reports from generating statistics, comparing performance graphs 
      to identifying playing patterns and automated highlights generation. It also removes any unnecessary video footage keeping only the points that are played in context. 
      Studio clips shots from rallies and helps players search for patterns of shots in the game."
    >
      <TwProduct
        name={"Studio"}
        icon={<IoMdAnalytics />}
        simpleDescription={"AI Based Video Analytics Platform"}
        description={
          "A state of the art AI based Video Analytics platform which provides with valuable insights to your game. " +
          "Just upload your match to get results generated by Reticulo's AI. " +
          "Studio provides a wide range of reports from generating statistics, comparing performance graphs to identifying playing patterns " +
          " and automated highlights generation. It also removes any unnecessary video footage keeping only the points that are played in context. " +
          "Studio clips shots from rallies and helps players search for patterns of shots in the game."
        }
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-w-3xl mx-auto">
          <a className="rounded-lg bg-indigo-600 text-white px-5 py-3 text-center shadow-soft hover:bg-indigo-700" href="https://studio.reticulo.in" target="_blank" rel="noreferrer">Go to Studio</a>
          <a className="rounded-lg border border-slate-300 px-5 py-3 text-center hover:border-slate-400" href="https://www.youtube.com/watch?v=nN_4CxG2TRI" target="_blank" rel="noreferrer">Click here to see a Demo!</a>
        </div>

        <FeatureSection
          key={0}
          name="Physical Statistics"
          description="Get accurate statistics of physical performance"
          featurePlacement={TwItemPlacement.RIGHT}
          featureType={TwFeatureType.IMAGE}
          featureUrl={"/studio/Player-Stats.png"}
        />
        <FeatureSection
          key={1}
          name="Hit Statistics"
          description="Get accurate statistics of shots played by players"
          featurePlacement={TwItemPlacement.LEFT}
          featureType={TwFeatureType.IMAGE}
          featureUrl={"/studio/General-Stats.png"}
        />
        <FeatureSection
          key={2}
          name="Graphs"
          description="Compare Performance Graphs between players"
          featurePlacement={TwItemPlacement.RIGHT}
          featureType={TwFeatureType.IMAGE}
          featureUrl="/studio/graphs.png"
        />
        <FeatureSection
          key={3}
          name="Reports"
          description="Match wise reports for detailed analysis"
          featurePlacement={TwItemPlacement.LEFT}
          featureType={TwFeatureType.IMAGE}
          featureUrl="/studio/reports.png"
        />
        <FeatureSection
          key={4}
          name="Advanced Video Player"
          description="A video player designed for Analysis of your game by viewing rally by rally, based on movements, based on shot patterns or based on shots"
          featurePlacement={TwItemPlacement.RIGHT}
          featureType={TwFeatureType.IMAGE}
          featureUrl="/studio/By-Rally.png"
        />
        <FeatureSection
          key={5}
          name="Shot Patterns"
          description="Identify and search for Shot Patterns of play and strategize accordingly"
          featurePlacement={TwItemPlacement.LEFT}
          featureType={TwFeatureType.IMAGE}
          featureUrl="/studio/Shot-Pattern.png"
        />
        <FeatureSection
          key={6}
          name="Drawing Tool and annotator tool"
          description="In-editor tool to understand and visualize strategy"
          featurePlacement={TwItemPlacement.RIGHT}
          featureType={TwFeatureType.IMAGE}
          featureUrl="/studio/By-Rally.png"
        />
        <FeatureSection
          key={6}
          name="Shot based videos"
          description="AI automatically creates shot based videos for easier access"
          featurePlacement={TwItemPlacement.LEFT}
          featureType={TwFeatureType.IMAGE}
          featureUrl="/studio/Shots.png"
        />
      </TwProduct>
    </SEOWrapper>
  );
};

export default Studio;
