import { SEOWrapper } from "@/components/SEO";
import TwProduct from "@/components/tw/Product";
import {
  IoAnalyticsOutline,
  IoBarChartOutline,
  IoDocumentTextOutline,
  IoCutOutline,
  IoSearchOutline,
} from "react-icons/io5";

const Studio = () => {
  return (
    <SEOWrapper
      title="Reticulo | Studio"
      description="A state of the art AI based Video Analytics platform which provides with valuable insights to your game. 
      Just upload your match to get results generated by Reticulo's AI. Studio provides a wide range of reports from generating statistics, comparing performance graphs 
      to identifying playing patterns and automated highlights generation. It also removes any unnecessary video footage keeping only the points that are played in context. 
      Studio clips shots from rallies and helps players search for patterns of shots in the game."
    >
      <main className="pt-20">
        <TwProduct
          name={"Studio"}
          icon={<IoAnalyticsOutline color="indigo" fontSize={28} />}
          simpleDescription={"AI Based Video Analytics Platform"}
          description={
            "A state of the art AI based Video Analytics platform which provides with valuable insights to your game. " +
            "Just upload your match to get results generated by Reticulo's AI. " +
            "Studio provides a wide range of reports from generating statistics, comparing performance graphs to identifying playing patterns " +
            " and automated highlights generation. It also removes any unnecessary video footage keeping only the points that are played in context. " +
            "Studio clips shots from rallies and helps players search for patterns of shots in the game."
          }
        >
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-w-3xl mx-auto">
            <a
              className="rounded-lg bg-indigo-600 text-white px-5 py-3 text-center shadow-soft hover:bg-indigo-700"
              href="https://studio.reticulo.in"
              target="_blank"
              rel="noreferrer"
            >
              Go to Studio
            </a>
            <a
              className="rounded-lg border border-slate-300 dark:border-slate-700 px-5 py-3 text-center hover:border-slate-400 dark:hover:border-slate-600"
              href="https://www.youtube.com/watch?v=nN_4CxG2TRI"
              target="_blank"
              rel="noreferrer"
            >
              Click here to see a Demo!
            </a>
          </div>

          <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-4 max-w-5xl mx-auto">
            {[
              {
                icon: IoAnalyticsOutline,
                title: "Physical Statistics",
                desc: "Accurate statistics for physical performance.",
              },
              {
                icon: IoBarChartOutline,
                title: "Hit Statistics",
                desc: "Detailed shot metrics and distribution.",
              },
              {
                icon: IoBarChartOutline,
                title: "Graphs",
                desc: "Compare performance trends across players.",
              },
              {
                icon: IoDocumentTextOutline,
                title: "Reports",
                desc: "Match-wise reports for deep analysis.",
              },
              {
                icon: IoCutOutline,
                title: "Advanced Video Player",
                desc: "Rally-based playback and pattern views.",
              },
              {
                icon: IoSearchOutline,
                title: "Shot Patterns",
                desc: "Identify, search and strategize on patterns.",
              },
              {
                icon: IoCutOutline,
                title: "Drawing & Annotation",
                desc: "In-editor tools to visualize strategy.",
              },
              {
                icon: IoCutOutline,
                title: "Shot-based Videos",
                desc: "AI compiles shot-based highlight reels.",
              },
            ].map(({ icon: Icon, title, desc }) => (
              <div
                key={title}
                className="flex items-start gap-3 p-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-soft"
              >
                <div className="h-10 w-10 rounded-lg bg-indigo-600 text-white flex items-center justify-center">
                  <Icon size={20} />
                </div>
                <div>
                  <div className="font-semibold text-slate-900 dark:text-white">
                    {title}
                  </div>
                  <div className="text-sm text-slate-600 dark:text-slate-300">
                    {desc}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </TwProduct>
      </main>
    </SEOWrapper>
  );
};

export default Studio;
